-- 004: v2 org-management — extension devices, join codes, org policy, device fields
-- Additive only: new tables, new columns, new policies. No drops, no deletes.

-- Org-level policy + feature flags (defaults per the brief confidence ladder)
alter table organisations
  add column if not exists warn_threshold double precision not null default 0.7,
  add column if not exists block_threshold double precision not null default 0.9,
  add column if not exists monitor_only boolean not null default false,
  add column if not exists feature_flags jsonb not null default '{}'::jsonb;

-- Extension devices: one row per browser instance that joined the org.
-- token_hash = sha256 hex of the device token. Never store the token itself.
create table if not exists extension_devices (
  id uuid primary key default gen_random_uuid(),
  org_id uuid references organisations(id) on delete cascade,
  user_email text not null default 'unknown',
  device_name text,
  token_hash text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  revoked_at timestamptz,
  expires_at timestamptz
);

-- One-time join codes generated by an org admin (shown once, hashed at rest)
create table if not exists extension_join_codes (
  id uuid primary key default gen_random_uuid(),
  org_id uuid references organisations(id) on delete cascade,
  created_by text,
  code_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz
);

-- Events gain device attribution
alter table events
  add column if not exists device_id uuid,
  add column if not exists device_name text;

create index if not exists extension_devices_token_hash_idx on extension_devices(token_hash);
create index if not exists extension_devices_org_idx on extension_devices(org_id);
create index if not exists extension_join_codes_code_hash_idx on extension_join_codes(code_hash);

-- RLS: org members can see and update their org's devices / join codes.
-- (Edge functions use the service role and bypass RLS; these policies serve the dashboard.)
alter table extension_devices enable row level security;
alter table extension_join_codes enable row level security;

create policy "org devices visible to members" on extension_devices
  for select using (org_id = (select org_id from user_profiles where id = auth.uid()));

create policy "org devices updatable by members" on extension_devices
  for update using (org_id = (select org_id from user_profiles where id = auth.uid()));

create policy "org join codes visible to members" on extension_join_codes
  for select using (org_id = (select org_id from user_profiles where id = auth.uid()));

create policy "org join codes deletable by members" on extension_join_codes
  for delete using (org_id = (select org_id from user_profiles where id = auth.uid()));
